// SPDX-FileCopyrightText: Copyright 2026 Stacklok, Inc.
// SPDX-License-Identifier: LicenseRef-Stacklok-Proprietary

// This file renders the generated, committed traceability matrix at
// docs/acceptance/traceability.md (actrace --matrix). The output is
// deterministic — plans sorted by path, ACs in parsed order, no timestamps — so
// `task verify-gen` can gate it on byte-stability. The matrix never gates: a
// draft plan with not-yet-built tests renders its gaps as `❌ unmet` rather than
// exiting non-zero. Issue #443, mechanism under ADR-0065.

package actrace

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// matrixHeader is the static do-not-edit preamble. It carries no timestamp on
// purpose: verify-gen gates the file on byte-stability, and a timestamp would
// churn the diff on every run.
const matrixHeader = `# Acceptance traceability matrix

This file is generated by ` + "`actrace --matrix`" + ` (` + "`task ac-trace-matrix`" + `); do
not edit it by hand. Run ` + "`task gen`" + ` and commit the result — ` + "`task verify-gen`" + `
fails if it is stale.

It maps every acceptance criterion under ` + "`docs/acceptance/`" + ` to its proof.
The ` + "`verify:`" + ` convention and the gate that enforces it on landed plans
live in [` + "`README.md`" + `](README.md) and
[ADR-0065](../adr/0065-acceptance-criteria-carry-verify-field-gated-by-actrace.md).
The freshly-computed JSON form, with source-file deep links, is
` + "`actrace --json`" + ` (` + "`task ac-trace-json`" + `).

Status encoding: ✅ test (a Go test resolves) · ✅ e2e (a Playwright spec
under ui/tests/e2e/ resolves) · ✅ unit (a vitest spec under ui/src/**
resolves) · ⚠️ unit (opt-out) (unit-only, waived by ` + "`ui-unit-ok:`" + `) ·
🔎 inspection (verified by review or a non-test method) · ⚪ none (deliberately
unverified, reserved or unreachable) · ❌ unmet (a named proof does not
resolve) · 🔶 untracked (no ` + "`verify:`" + ` field).

`

// glyphs for the per-AC status column.
const (
	glyphTest       = "✅ test"
	glyphE2E        = "✅ e2e"
	glyphUnit       = "✅ unit"
	glyphUnitOptOut = "⚠️ unit (opt-out)"
	glyphInspection = "🔎 inspection"
	glyphNone       = "⚪ none"
	glyphUnmet      = "❌ unmet"
	glyphUntracked  = "🔶 untracked"
)

// renderMatrix produces the full matrix Markdown for the given plans. The input
// is rendered as-is (the caller sorts by path); ACs keep their parsed order.
func renderMatrix(plans []PlanCoverage) string {
	sorted := append([]PlanCoverage(nil), plans...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Path < sorted[j].Path })

	var b strings.Builder
	b.WriteString(matrixHeader)
	writeRollup(&b, sorted)
	for _, p := range sorted {
		writePlanSection(&b, p)
	}
	return b.String()
}

// writeRollup writes the repo roll-up table: one row per plan.
func writeRollup(b *strings.Builder, plans []PlanCoverage) {
	b.WriteString("## Roll-up\n\n")
	b.WriteString("| Plan | Status | test-proven | by-inspection | unmet | untracked | stale? |\n")
	b.WriteString("|------|--------|-------------|---------------|-------|-----------|--------|\n")
	for _, p := range plans {
		stale := ""
		if p.Stale {
			stale = "yes"
		}
		fmt.Fprintf(b, "| [%s](%s) | %s | %d | %d | %d | %d | %s |\n",
			escapePipe(filepath.Base(p.Path)), filepath.Base(p.Path), p.Status,
			p.Counts.TestProven, p.Counts.ByInspect, p.Counts.Unmet,
			p.Counts.Unannotated, stale)
	}
	b.WriteString("\n")
}

// writePlanSection writes one plan's `##` section. A fully-proven landed plan
// collapses to a one-line summary; a draft plan collapses to nothing beyond its
// roll-up row; every other plan lists its ACs grouped by scenario.
func writePlanSection(b *strings.Builder, p PlanCoverage) {
	fmt.Fprintf(b, "## %s\n\n", escapePipe(filepath.Base(p.Path)))
	fmt.Fprintf(b, "Status: %s.\n\n", p.Status)

	if p.Status == "draft" || p.Status == "in-progress" {
		b.WriteString("Draft plan — criteria are tracked but not yet gated; see the JSON form for current proof state.\n\n")
		return
	}
	if p.Status == "landed" && p.Counts.ACs > 0 && fullyProven(p) {
		fmt.Fprintf(b, "All %d criteria proven.\n\n", p.Counts.ACs)
		return
	}
	writeACTables(b, p.ACs)
}

// fullyProven reports whether every criterion in a plan is proven by a resolving
// test or ui spec — the collapse condition for a landed plan.
func fullyProven(p PlanCoverage) bool {
	for _, ac := range p.ACs {
		if ac.Status != acStatusProven {
			return false
		}
	}
	return true
}

// writeACTables writes the per-scenario AC tables for a plan, in the order the
// scenarios first appear. ACs with no scenario heading go under an "(ungrouped)"
// section so none is dropped.
func writeACTables(b *strings.Builder, acs []ACCoverage) {
	var order []string
	groups := map[string][]ACCoverage{}
	for _, ac := range acs {
		key := ac.Scenario
		if key == "" {
			key = "(ungrouped)"
		}
		if _, ok := groups[key]; !ok {
			order = append(order, key)
		}
		groups[key] = append(groups[key], ac)
	}
	for _, key := range order {
		fmt.Fprintf(b, "### %s\n\n", escapePipe(key))
		b.WriteString("| AC | status | proof |\n")
		b.WriteString("|----|--------|-------|\n")
		for _, ac := range groups[key] {
			fmt.Fprintf(b, "| %s | %s | %s |\n", ac.ID, acGlyph(ac), escapePipe(acProof(ac)))
		}
		b.WriteString("\n")
	}
}

// acGlyph returns the glyph + word for a criterion's status. A method AC reads
// 🔎 inspection unless its method word is "none", which reads ⚪ none. A proven
// AC whose proofs are all front-end specs reads ✅ e2e when at least one
// resolves under ui/tests/e2e/, ✅ unit when all resolve under ui/src/**, or
// ⚠️ unit (opt-out) when unit-only and waived by a `ui-unit-ok:` reason;
// otherwise it reads ✅ test (a Go test is in the proof set).
func acGlyph(ac ACCoverage) string {
	switch ac.Status {
	case acStatusUnannotated:
		return glyphUntracked
	case acStatusMissing:
		return glyphUnmet
	case acStatusMethod:
		if len(ac.Proofs) > 0 && ac.Proofs[0].Method == "none" {
			return glyphNone
		}
		return glyphInspection
	case acStatusProven:
		if allUI(ac.Proofs) {
			if anyE2E(ac.Proofs) {
				return glyphE2E
			}
			if ac.OptOut != "" {
				return glyphUnitOptOut
			}
			return "❌ unit (no e2e)"
		}
		return glyphTest
	default:
		return glyphUntracked
	}
}

// allUI reports whether every proof is a front-end spec (so the proven glyph is
// ✅ e2e / ✅ unit rather than ✅ test).
func allUI(proofs []Proof) bool {
	if len(proofs) == 0 {
		return false
	}
	for _, p := range proofs {
		if p.Kind != proofKindUI {
			return false
		}
	}
	return true
}

// anyE2E reports whether any front-end proof resolves to a Playwright e2e spec
// under ui/tests/e2e/ — the render-from-wire proof the gate requires.
func anyE2E(proofs []Proof) bool {
	for _, p := range proofs {
		if p.Kind == proofKindUI && p.Resolves && p.FEKind == feKindE2E {
			return true
		}
	}
	return false
}

// acProof renders a criterion's proof cell. A method AC always shows its reason.
// A test/ui AC lists the proof refs. Resolved source-file paths are deliberately
// omitted — they churn on refactors and belong only in the JSON form.
func acProof(ac ACCoverage) string {
	switch ac.Status {
	case acStatusUnannotated:
		return "—"
	case acStatusMethod:
		if len(ac.Proofs) == 0 {
			return "—"
		}
		p := ac.Proofs[0]
		if p.Reason == "" {
			return p.Method
		}
		return fmt.Sprintf("%s — %s", p.Method, p.Reason)
	default:
		var refs []string
		for _, p := range ac.Proofs {
			ref := "`" + p.Ref + "`"
			if !p.Resolves {
				ref += " (missing)"
			}
			refs = append(refs, ref)
		}
		if len(refs) == 0 {
			return "—"
		}
		joined := strings.Join(refs, ", ")
		if ac.OptOut != "" {
			joined += "; ui-unit-ok: " + ac.OptOut
		}
		return joined
	}
}

// escapePipe escapes `|` so a cell value does not break the Markdown table.
func escapePipe(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}
