// SPDX-FileCopyrightText: Copyright 2026 Stacklok, Inc.
// SPDX-License-Identifier: Apache-2.0

package actrace

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// fixturePlans is a small, hand-built plan set covering every collapse and
// glyph branch the matrix renders: a fully-proven landed plan (collapses to a
// summary line), a landed plan with a mix of proven / method / unmet / ui ACs
// (renders full scenario tables), and a draft plan (collapses to the roll-up
// row plus a draft note). The pipe in a method reason exercises escaping.
func fixturePlans() []PlanCoverage {
	full := PlanCoverage{
		Path:   "docs/acceptance/zeta-fully-proven.md",
		Status: "landed",
		Mode:   "structured",
		ACs: []ACCoverage{
			{ID: "AC1.1", Scenario: "Scenario 1 — A", Status: acStatusProven,
				Proofs: []Proof{{Ref: "TestADR_0065_A", Kind: proofKindTest, Resolves: true, File: "a_test.go"}}},
			{ID: "AC1.2", Scenario: "Scenario 1 — A", Status: acStatusProven,
				Proofs: []Proof{{Ref: "TestADR_0065_B", Kind: proofKindTest, Resolves: true, File: "b_test.go"}}},
		},
	}
	full.Counts = countPlan(full.ACs)

	mixed := PlanCoverage{
		Path:   "docs/acceptance/alpha-mixed.md",
		Status: "landed",
		Mode:   "structured",
		ACs: []ACCoverage{
			{ID: "AC1.1", Scenario: "Scenario 1 — Core", Status: acStatusProven,
				Proofs: []Proof{{Ref: "TestADR_0065_Core", Kind: proofKindTest, Resolves: true, File: "core_test.go"}}},
			{ID: "AC1.2", Scenario: "Scenario 1 — Core", Status: acStatusMethod,
				Proofs: []Proof{{Ref: "none — reserved | unreachable", Kind: proofKindMethod, Method: "none", Reason: "reserved | unreachable"}}},
			{ID: "AC1.3", Scenario: "Scenario 1 — Core", Status: acStatusMethod,
				Proofs: []Proof{{Ref: "inspection — by construction", Kind: proofKindMethod, Method: "inspection", Reason: "by construction"}}},
			{ID: "AC2.1", Scenario: "Scenario 2 — UI", Status: acStatusProven,
				Proofs: []Proof{{Ref: "ui-e2e:chat-stream", Kind: proofKindUI, Resolves: true, File: "ui/tests/e2e/chat-stream.spec.ts", FEKind: "e2e"}}},
			{ID: "AC2.2", Scenario: "Scenario 2 — UI", Status: acStatusMissing,
				Proofs: []Proof{{Ref: "TestADR_0065_Gone", Kind: proofKindTest, Resolves: false}}},
			{ID: "AC2.3", Scenario: "Scenario 2 — UI", Status: acStatusProven, OptOut: "pure URL sanitizer, no wire render",
				Proofs: []Proof{{Ref: "ui-unit:safe-url", Kind: proofKindUI, Resolves: true, File: "ui/src/lib/safe-url.test.ts", FEKind: "unit"}}},
		},
	}
	mixed.Counts = countPlan(mixed.ACs)

	draft := PlanCoverage{
		Path:   "docs/acceptance/beta-draft.md",
		Status: "draft",
		Mode:   "prose",
		ACs: []ACCoverage{
			{ID: "AC1.1", Status: acStatusUnannotated},
		},
	}
	draft.Counts = countPlan(draft.ACs)

	return []PlanCoverage{full, mixed, draft}
}

// TestADR_0065_TraceabilityMatrixGolden pins the structural shape of the
// generated traceability matrix (ADR-0065): plans sorted by path, a
// repo roll-up table, a fully-proven landed plan collapsed to a summary line, a
// draft plan collapsed to a note, a mixed landed plan rendered as per-scenario
// AC tables with glyph+word status, method ACs always showing their reason, a
// `|` escaped in a cell, and no source-file path leaking into the Markdown.
func TestADR_0065_TraceabilityMatrixGolden(t *testing.T) {
	t.Parallel()
	got := renderMatrix(fixturePlans())

	// Static, do-not-edit header with no timestamp.
	assert.Contains(t, got, "# Acceptance traceability matrix")
	assert.Contains(t, got, "generated by `actrace --matrix`")

	// Roll-up table present with one row per plan, sorted by path.
	rollup := section(t, got, "## Roll-up", "## ")
	assert.Contains(t, rollup, "| Plan | Status | test-proven | by-inspection | unmet | untracked | stale? |")
	assert.Contains(t, rollup, "| [alpha-mixed.md](alpha-mixed.md) | landed | 3 | 2 | 1 | 0 |  |")
	assert.Contains(t, rollup, "| [beta-draft.md](beta-draft.md) | draft | 0 | 0 | 0 | 1 |  |")
	assert.Contains(t, rollup, "| [zeta-fully-proven.md](zeta-fully-proven.md) | landed | 2 | 0 | 0 | 0 |  |")

	// Sort order: alpha before beta before zeta, in the roll-up and the sections.
	assert.Less(t, strings.Index(got, "alpha-mixed.md"), strings.Index(got, "beta-draft.md"))
	assert.Less(t, strings.Index(got, "beta-draft.md"), strings.Index(got, "zeta-fully-proven.md"))

	// Fully-proven landed plan collapses to a one-line summary, no AC table.
	zeta := section(t, got, "## zeta-fully-proven.md", "")
	assert.Contains(t, zeta, "All 2 criteria proven.")
	assert.NotContains(t, zeta, "| AC |")

	// Pre-landed plan collapses to a note, no AC table.
	beta := section(t, got, "## beta-draft.md", "## zeta")
	assert.Contains(t, beta, "Pre-landed plan")
	assert.NotContains(t, beta, "| AC |")

	// Mixed landed plan renders per-scenario AC tables with glyph + word.
	alpha := section(t, got, "## alpha-mixed.md", "## beta")
	assert.Contains(t, alpha, "### Scenario 1 — Core")
	assert.Contains(t, alpha, "### Scenario 2 — UI")
	assert.Contains(t, alpha, "| AC1.1 | ✅ test | `TestADR_0065_Core` |")
	assert.Contains(t, alpha, "| AC2.1 | ✅ e2e | `ui-e2e:chat-stream` |")
	assert.Contains(t, alpha, "| AC2.2 | ❌ unmet | `TestADR_0065_Gone` (missing) |")
	// A unit-only AC waived by `ui-unit-ok:` reads ⚠️ unit (opt-out) and the
	// proof cell appends the opt-out reason.
	assert.Contains(t, alpha, "| AC2.3 | ⚠️ unit (opt-out) | `ui-unit:safe-url`; ui-unit-ok: pure URL sanitizer, no wire render |")
	// Method ACs always show their reason; "none" reads ⚪ none, others 🔎.
	assert.Contains(t, alpha, "| AC1.2 | ⚪ none | none — reserved \\| unreachable |")
	assert.Contains(t, alpha, "| AC1.3 | 🔎 inspection | inspection — by construction |")

	// A `|` inside a method reason is escaped so it does not break the cell.
	assert.NotContains(t, alpha, "reserved | unreachable |")

	// Source-file paths never appear in the Markdown — they belong in --json only.
	assert.NotContains(t, got, "core_test.go")
	assert.NotContains(t, got, "ui/tests/e2e/chat-stream.spec.ts")
	assert.NotContains(t, got, "ui/src/lib/safe-url.test.ts")
}

// section returns the substring of doc from the first occurrence of start up to
// the next occurrence of end after it (or to the document end when end is "" or
// not found). It lets the golden assertions scope a Contains/NotContains to one
// plan's section without depending on the rest of the document's exact bytes.
func section(t *testing.T, doc, start, end string) string {
	t.Helper()
	i := strings.Index(doc, start)
	require.GreaterOrEqual(t, i, 0, "section start %q must be present", start)
	rest := doc[i+len(start):]
	if end == "" {
		return rest
	}
	if j := strings.Index(rest, end); j >= 0 {
		return rest[:j]
	}
	return rest
}

// TestADR_0065_TraceabilityJSONShape pins the --json automation interface
// (ADR-0065): the freshly-computed Report round-trips through JSON
// with the documented field names, a test proof carries its resolved source
// file (the deep link the Markdown omits), a method proof carries its method
// word and reason, and an unmet proof reports resolves=false.
func TestADR_0065_TraceabilityJSONShape(t *testing.T) {
	t.Parallel()
	rep := Report{
		Plans: fixturePlans(),
		Backward: BackwardResult{
			Violations: []string{"TestADR_9999_Dangling"},
		},
		Orphans: OrphanResult{
			Scanned:   3,
			Excused:   []string{"TestFoo_Scenario1_Smoke"},
			Untracked: []string{"TestFoo_Scenario2_Real"},
		},
	}

	b, err := json.Marshal(rep)
	require.NoError(t, err)

	var round Report
	require.NoError(t, json.Unmarshal(b, &round))
	assert.Equal(t, rep, round, "Report must round-trip through JSON unchanged")

	// Field names are the documented automation contract.
	var generic map[string]any
	require.NoError(t, json.Unmarshal(b, &generic))
	assert.Contains(t, generic, "plans")
	assert.Contains(t, generic, "backward")
	assert.Contains(t, generic, "orphans")

	// The mixed plan's proofs carry the surfaces the Markdown drops.
	mixed := round.Plans[1]
	require.Equal(t, "docs/acceptance/alpha-mixed.md", mixed.Path)
	assert.Equal(t, "core_test.go", mixed.ACs[0].Proofs[0].File, "test proof carries its source file in JSON")
	assert.Equal(t, "none", mixed.ACs[1].Proofs[0].Method, "method proof carries its method word")
	assert.Equal(t, "reserved | unreachable", mixed.ACs[1].Proofs[0].Reason, "method proof carries its reason verbatim")
	assert.False(t, mixed.ACs[4].Proofs[0].Resolves, "an unmet proof reports resolves=false")

	assert.Equal(t, []string{"TestADR_9999_Dangling"}, round.Backward.Violations)
	assert.Equal(t, []string{"TestFoo_Scenario2_Real"}, round.Orphans.Untracked)
}
